name: 'Pipeline Orchestrator'
description: 'Orchestrate the pipeline'
inputs:
  aws_access_key_id:
    description: Key Id
    required: true
  aws_secret_access_key:
    description: Secret Key
    required: true
  run_env:
    description: 'Run environment: [dev, qa, uat, prod]'
    required: true
  parallelize:
    description: 'Should projects be deployed as separate builds?'
    required: false
  slack_webhook:
    description: 'Send alerts for success/failure of builds'
    required: false
  debug:
    description: 'Set codebuild run into debug mode'
    required: false
  gemfury_token:
    description: 'Push/pull gemfury token'
    required: false
  argo_skip_envs:
    description: 'Skip argo deployment for list of environments'
    required: false
runs:
  using: "composite"
  steps:
    - name: Invoke orchestrator codebuild
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        RUN_ENV: ${{ inputs.run_env }}
        PARALLELIZE: ${{ inputs.parallelize }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        DEBUG: ${{ inputs.debug }}
        GEMFURY_TOKEN: ${{ inputs.gemfury_token }}
        ARGO_SKIP_ENVS: ${{ inputs.argo_skip_envs }}
      run: |
        echo "Build will run env-specific deploys in ${{ inputs.run_env }} environment."
        export AWS_DEFAULT_REGION=us-east-1

        cd ../../_actions/Snagajob/devops.action.orchestrator/master
        pip3 -q install -r requirements.txt
        python3 bootstrap.py

