name: 'Pipeline Orchestrator'
description: 'Orchestrate the pipeline'
inputs:
  run_env:
    description: 'Run environment: [dev, qa, uat, prod]'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt install python3-pip
        sudo pip install awscli
    - name: Invoke orchestrator codebuild
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      run: |
        echo "You want to deploy to the ${{ inputs.run_env }} environment."
        aws sts get-caller-identity
